### ISSUE TITLE
Supported FIX version(s)?

### ISSUE THREAD

**Issue by JohnGreenan** [AlignmentSystems/PyEngine#12]
Do we have a model such as quickfix/j where protocol violations such as a "new" custom tag may cause the engine to drop the session?

Which version(s) do we support?

How do we handle custom tags?

Do we support a data dictionary or just pass-through tags to an abstraction layer?

**Comment by da4089** [comment]
In previous lives, I've not bothered with strict protocol validation.  Where I was translating the FIX message into another protocol or a database row, I ensured that required fields were present, and that all recognized fields had correct data types.  In some cases, I've reported fields that were present, but not recognised.

I've never dropped the session for extraneous tags, but I can see that in some cases that'd be reasonable.  It's easy enough to do.  Using a QuickFIX-style schema, and enforcing it is fairly simple.

I've not implemented the FIX-5.x recovery logic before, but otherwise I've supported FIX 4.0 onwards.  ExecTransType has been the biggest translation issue I've run into previously.

An optional schema enforcement could be added if needed.
